name:  sockjs_client
version: 0.2.0
authors:
- Nelson Silva <nelson.silva@inevo.pt>
- Sébastien Deleuze
description:  A SockJS client in Dart
dependencies:
  browser: '>=0.9.0 <1.0.0'
  logging: '>=0.9.0 <1.0.0'
  stomp:
environment:
  sdk: '>=1.0.0 <2.0.0'